add_rules("mode.debug", "mode.release")

target("yir-pipeline-analyzer")
    set_kind("binary")
    set_languages("c++17")
    add_includedirs("../../include")
    add_files("main.cpp", "liveness_analysis.cpp", "pipeline_diff.cpp")
    add_files("../../src/yir/**.cpp")
    add_files("../../src/ast/**.cpp")
    add_files("../../src/pass/yir/**.cpp")
    add_files("../../src/pass/ast/ASTSemanticAnalysisPass.cpp")
    add_files("../../src/pass/ast/ASTToYIRPass.cpp")
    add_files("../../src/pass/PassManager.cpp")
    add_files("../../src/front/**.cpp")
